[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"

[environments.production.variables]
FLASK_ENV = "production"
PYTHONPATH = "."

